name: Angular Test Workflow On All Branches
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Angular CLI
        run: |
          npm install -g @angular/cli
          echo "Angular CLI installed successfully"

      - name: Configure Puppeteer
        run: npm install puppeteer

      - name: Run tests
        id: test
        run: ng test --watch=false --browsers=ChromeHeadless

      - name: Build Docker image
        if: github.ref == 'refs/heads/dev'  && steps.test.outcome == 'success'
        run: |
          docker build -t angular-app .
        working-directory: "C:\Users\User\Desktop\University\sem5\1- cicd\Angular-CICD-Sample\angular-sum-calculator"


      - name: Run Docker container
        if: github.ref == 'refs/heads/dev'  && steps.test.outcome == 'success'
        run: |
          docker run -d -p 4200:4200 angular-app
        ports:
          - 4200:4200
        env:
          - NODE_ENV=production
