name: Angular Test Workflow On All Branches
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Angular CLI
        run: |
          npm install -g @angular/cli
          echo "Angular CLI installed successfully"

      - name: Configure Puppeteer
        run: npm install puppeteer

      - name: Run tests
        id: test
        run: ng test --watch=false --browsers=ChromeHeadless

      - name: Stop and Remove Running Containers
        if: github.ref == 'refs/heads/dev'
        run: |
          # Stop and remove containers using the image (if any)
          docker stop my-calculator-angular-app-container || true
          docker rm my-calculator-angular-app-container || true

      - name: Remove Previous Docker Image
        if: github.ref == 'refs/heads/dev'
        run: |
          # Remove the existing Docker image if it exists
          docker rmi -f my-calculator-angular-app || true

      - name: Create Docker image
        if: github.ref == 'refs/heads/dev'  && steps.test.outcome == 'success'
        run: |
          docker build -t my-calculator-angular-app .

      - name: Run Docker Container
        if: github.ref == 'refs/heads/dev'  && steps.test.outcome == 'success'
        run: |
          docker run -p 8080:4200 --name my-calculator-angular-app-container -d my-calculator-angular-app
